config/routes.rb
Rails.application.routes.draw do
  get 'orders/show'
  devise_for :users
  resources :carts
  resources :items
  resources :orders
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :items
	has_many :users
	has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord

	has_many :carts
	has_many :orders, through: :carts

	validates :title, presence: true
	validates :description, presence: true
	validates :price, length: { minimum: 1 }
	
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :user
	belongs_to :cart, optional: true
	belongs_to :item
	

	after_create :Order_send


	def Order_send
		UserMailer.Order_info(User).deliver_now
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :cart, optional: true
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

def create

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController


  def index 
  	@cart = current_user.cart

    puts "#" *60
    puts @cart.item_id
    puts "#" *60
  @item = Item.find(@cart[:item_id])
  end

  def create
  	@user = current_user
  	@cart = Cart.create!
  	@user.update(cart: @cart)
  	puts "#" *60
  	puts @user.cart
  	puts "#" *60
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index

		@items = Item.all

		if user_signed_in? && current_user.cart == nil
			@cart = Cart.create!
			current_user.update(cart: @cart)
		end

	end
	
	def show
		puts "#" *60
  	puts current_user.cart.id
  	puts "#" *60
		@item = Item.find(params[:id])
	end

	def update
		
		@item = Item.find(params[:id])

		if user_signed_in? 

			@cart = Cart.find(current_user.cart[:id])

			@cart.update(item_id: @item.id)
			puts "#"*60
			puts @cart.item_id
			puts "#"*60

			redirect_to root_path

		else
			redirect_to item_path(@item.id)

		end 

	end 

	include ApplicationHelper

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  	@cart = Cart.find(current_user.cart[:id])
  	@order = Item.find(@cart.item_id)
  	puts "#"*60
  	puts @cart.item_id
  	puts "#"*60
  	
  end

  def create

  	@cart = Cart.find(current_user.cart[:id])
    @item = Item.find(@cart[:item_id])
  	puts "#"*60
  	puts @item
  	puts "#"*60
  	@order = Order.create!(user: current_user, item: @item )
  	@cart.destroy
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  	@user = User.find(params[:id])

  end

  def edit
  	
  end

  def update

  	@user = Task.find(params[:id])
  	@user.update(user_params)

    flash[:notice] = "User edited"

  end 

  

  private

  def user_params
    params.permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/carts/index.html.erb
<% if @cart.item_id == nil %>

<div class="list-group-item" id="empty-cart">
	<h2 class="text-center">Your cart is empty!</h2>
	<p class="text-center"><%= link_to "Back home", root_path %></p>
</div>

<% else %>

	<h1 class="index-title"> Your cart:</h1>

	<ul class="list-group-cart">

		<li class="list-group-item d-flex justify-content-between align-items-center list-checkout-cart">

			<div class="item-details-container">
				<%= image_tag "#{@item.image_url}", alt: "image", class: "product-image" %>				
			</div>
				<div class="item-title-description">
					<h3><%= link_to @item.title, item_path(@item.title)%></h3>
					<small class="text-muted description-text-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at quam placerat, aliquet ex et, rhoncus erat. Pellentesque faucibus semper magna, id blandit enim eleifend egestas. Duis iaculis ut est in pulvinar.</small>
			</div>

			<div class="price-container">
				<%= @item.price %>€
			</div>

			<div class="quantity-button">
				<div class="form-group">
					<label for="selected1">Quantity: </label>
					<div class="inputndelete">
						<div>
							<select class="form-control" id="selected1">
								<option>1</option>
								<option>2</option>
								<option>3</option>
								<option>4</option>
								<option>5</option>
							</select>
						</div>

						<div class="trash-div">
							<%= link_to "XXXX", item_path(@item.id), method: :delete, :class => "fas fa-trash-alt" %>
						</div>
					</div>
				</div>
			</div>
		</li>	
	</ul>

<%end%>

app/views/items/index.html.erb
    <!-- Page Features -->
	<body>

<div class="container">
	<div class="d-flex flex-wrap">
	<% @items.each do |item| %>
    	<div class="cart-card col-lg-3 col-md-6 mb-4 text-center">
			<div class="card h-100" style="width: 100%;">
			<div class="my-image-container"></div>
			<div class="card-body">
				<h4 class="card-title"><%= item.title %></h4>
				<p class="card-text"><%= item.description %></p>
			</div>
			<div id="">
				<p class="card-text"><%= item.price %></p>
				</div>
					<div id="buttons">
					<div id="show-item-page">
						<%= link_to "Show item", item_path(item.id), class: "nav-link" %>
					</div>
				</div>
			</div>
    	</div>
	<%end%>
	</div>
</div>
	

</body>
<!-- <!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Accueil</title>
	</head>

	<body>

		<h1>Index</h1>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

    <li>
    	<%= link_to "Passer commande", "orders#index", method: :get %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

		<% @items.each do |item| %>
			<p>
				<%= item.title %>			
			</p> <br>
			<a href=" <%= item_path(item.id)%>"> Voir l'article </a>

		<%end%>

	</body>

</html>
-->

app/views/items/show.html.erb
<div class="card card-content mb-3">

  <h3 class="card-header" style="text-align: center;"> <%= @item.title %> </h3>

  <div class="my-image-container"></div>

    <div class="card-body" >

        <p class="card-text" style="float:left;"> <%= @item.price%> € </p> 



         <%= link_to "Ajouter au panier", item_path(@item.id), method: 'put', class:"card-link" %>

     </div>
</div> 

<br/> <br/>



<a href="<%= item_path(@item.id)%>" data-method="patch"> Ajouter au panier </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoutiqueEnLigne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>

<!-------------------------------Navbar--------------------------------->
     
<nav class="navbar navbar-expand-lg fixed-top" style="background: #DE9B9B">
  <div class="container">
    <a class="navbar-brand mr-sm-2"><%=link_to image_tag("Banner.svg", alt:"Chat Alors!", style:"height: 60px; width: 50%"), items_path%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
              <li class="nav-button">
                <%= link_to "Cart", "carts#show", class: "nav-link" %>
              </li>
              <li class="nav-button">
                <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-button">
                <%= link_to "Log out", destroy_user_session_path, :class => "nav-link", :method => :delete %>
              </li>   
            <% else %>
              <li class="nav-button">
                <%= link_to 'Sign up', new_user_registration_path, class: "nav-link", 'data-toggle' => "modal", 'data-target' => "#modalSignup" %>
              </li>
              <li class="nav-button">
                <%= link_to 'Log in', new_user_session_path, class: "nav-link", 'data-toggle' => "modal", 'data-target' => "#modalLogin" %>
              </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-------------------------------Body--------------------------------->
<body>
    <br/><br/><br/><br/><br/><br/>

    <%= yield %>
</body>
<!-------------------------------Footer--------------------------------->

<footer class="page-footer font-small pt-4" style="background: #DE9B9B">

  <div class="container-fluid text-center text-md-left">

    <div class="row">

      <div class="col-md-6 mt-md-0 mt-3">

        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>

      <hr class="clearfix w-100 d-md-none pb-3">

      <div class="col-md-3 mb-md-0 mb-3">

        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <div class="col-md-3 mb-md-0 mb-3">

        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
     

    </div>
   

  </div>
 

  
  <div class="footer-copyright text-center py-3">Made with the hacking project:
    <a href="https://www.thehackingproject.org"> MDBootstrap.com</a>
  </div>
 
</footer>

app/views/layouts/order_info.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Salut <%= @user.name %> et bienvenue chez nous !</h1>
    <p>
      Tu t'es inscrit sur monsite.fr en utilisant l'e-mail suivant : <%= @user.email %>.
    </p>
    <p>
      Pour accéder à ton espace client, connecte-toi via : <%= @url %>.
    </p>
    <p> À très vite sur monsite.fr !
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>
<%= @order.title %>
<%= link_to "Confirmer commande", "/orders", method: :post %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>